# db/ - Database layer
from db.connection import get_db, close_db
from db.movies import (
    get_user_watchlist,
    get_watchlist_counts,
    add_to_watchlist,
    remove_from_watchlist,
    is_in_watchlist,
    get_watchlist_movie,
    mark_as_watched,
    mark_as_unwatched,
    get_user_watched,
    add_to_watched,
    remove_from_watched,
    is_in_watched,
    get_user_pending,
    add_pending_suggestion,
    get_pending_by_movie_id,
    remove_pending_by_movie_id,
    get_movie_reviews,
    add_movie_review,
    get_random_review,
    get_all_reviews,
    format_reviewers_text,
)
from db.anime import (
    get_anime_watchlist,
    get_anime_watchlist_counts,
    add_to_anime_watchlist,
    remove_from_anime_watchlist,
    is_in_anime_watchlist,
    get_anime_watchlist_entry,
    mark_anime_as_watched,
    mark_anime_as_unwatched,
    get_anime_reviews,
    add_anime_review,
    get_random_anime_review,
    format_anime_reviewers_text,
)
